
services:
  app:
    image: ivo123/express-cicd:latest
    ports:
      - "3000:3000"

  watchtower:
    image: containrrr/watchtower
    container_name: watchtower
    environment:
      - WATCHTOWER_POLL_INTERVAL=60
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
